### ISSUE TITLE
Motion detector not triggering during siren 

### ISSUE THREAD

**Issue by Redball33** [DanZBo/homebridge-RedAlertViaKumta#1]
I have configured the plugin as per the instructions but motion is never detected 

Plugin logs are completely blank

2024-10-06T14:29:05.858] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
[2024-10-06T14:29:05.899] [INFO] - [Using LAYER 165 for initial connect]
[06/10/2024, 14:29:10] [RedAlertViaKumta] CONNECT TO TELEGRAM SUCCESS
[06/10/2024, 14:29:11] [RedAlertViaKumta] https://t.me/CumtaAlertsChannel subscribtion virified
[06/10/2024, 14:29:11] [RedAlertViaKumta] https://t.me/CumtaAlerts2Channel subscribtion virified

    "bridge": {
        "name": "Homebridge 7C68",
        "username": "B8:27:EB:EA:21:8C",
        "ip address": "192.168.cx.xx",
        "port": 51002,
        "pin": "649-cx-145",
        "advertiser": "ciao"
    },
    "accessories": [
        {
            "name": "Kitchen Timer",
            "delay": 600000,
            "delayUnit": "ms",
            "sensorType": "motion",
            "flipSensorState": false,
            "startOnReboot": false,
            "debug": false,
            "accessory": "DelaySwitch"
        },
        {
            "name": "Kids Timer",
            "delay": 600000,
            "sensorType": "motion",
            "flipSensorState": false,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
        },
        {
            "name": "Bedroom timer",
            "delay": 600,
            "delayUnit": "s",
            "sensorType": "motion",
            "flipSensorState": false,
            "startOnReboot": false,
            "debug": false,
            "accessory": "DelaySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "devices": [
                {
                    "name": "Robot Cleaner",
                    "ip": "192.168.x.cx",
                    "token": "xxxxcxxxccc34",
                    "deviceId": "xxxvxvx",
                    "model": "dreame.vacuum.p2027",
                    "pollingInterval": 1000,
                    "deepDebugLog": false,
                    "micloud": {
                        "username": "cxxxxxxx",
                        "password": "ccxxx. -ccxxxx",
                        "country": "us",
                        "forceMiCloud": false
                    },
                    "customAccessory": false,
                    "onlyMainService": true,
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": false,
                    "actionButtons": [
                        {
                            "action": "4.1",
                            "name": "Clean kitchen",
                            "params": [
                                "{\"selects\":[[11,3,1,3,1],[7,3,1,3,2],[5,1,1,1,3],[10,1,1,1,4]]}"
                            ]
                        }
                    ]
                }
            ],
            "platform": "miot"
        },
        {
            "name": "eWeLink",
            "username": "xxxxxx@cxx.com",
            "password": "xxxx-xxxxxcxudjaR",
            "mode": "lan",
            "language": "en",
            "fanDevices": [
                {
                    "label": "Bedroom Ceiling Fan",
                    "deviceId": "1001f1871b",
                    "deviceModel": "ifan",
                    "ipAddress": "192.168.x.19"
                }
            ],
            "platform": "eWeLink"
        },
        {
            "auth": "usernamePassword",
            "username": "xxxxx@cxxx.com",
            "password": "xxxxx-xxxx-burja7",
            "allowRepeatedCommands": false,
            "disableAirQuality": true,
            "disableCarbonDioxide": true,
            "disableDry": true,
            "disableFan": false,
            "disableHumidity": false,
            "externalHumiditySensor": false,
            "disableLightSwitch": false,
            "disableHorizontalSwing": true,
            "disableVerticalSwing": false,
            "enableClimateReactSwitch": false,
            "enableClimateReactAutoSetup": false,
            "climateReactSwitchInAccessory": false,
            "enableHistoryStorage": false,
            "enableOccupancySensor": false,
            "enableSyncButton": false,
            "syncButtonInAccessory": false,
            "ignoreHomeKitDevices": false,
            "modesToExclude": [
                "AUTO",
                "COOL",
                "DRY",
                "HEAT"
            ],
            "debug": false,
            "platform": "SensiboAC"
        },
        {
            "cities": "חריש, מטולה",
            "tg_api_id": "xxxxxxx",
            "tg_api_hash": "xxxxxxxx",
            "rockets_alerts_channel": "https://t.me/CumtaAlertsChannel",
            "terror_alerts_channel": "https://t.me/CumtaAlerts2Channel",
            "debug": true,
            "timeout": 7,
            "platform": "RedAlertViaKumtaj
**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by sobelman** [comment]
@Redball33 
Man, u uploaded all tokens and secrets here,
I would highly advice to reset all relevant tokens, hashes and secrets.

**Comment by Redball33** [comment]
Appreciate the advice. I don’t know how I would go about resetting it without deleting and re-creating the account.

**Comment by DanZBo** [comment]
Hello @Redball33 . We investigated your issue and we found a problem with plugin dependencies.  Please update the plugin to the latest version and wait for new motions. 
Also please update us about results in any case.

**Comment by Redball33** [comment]
IT WORKS!!

Thank you for the support. I don't see anywhere where I can buy you guys a beer/coffee but I would defiantly  like to make a contribution if at all possible.

**Comment by sobelman** [comment]
Hi, 
Great. 
Let's keep track it and if needed, please open a new issue. 

Thanks for the coffee :) All is good :) 

Closing this issue for now.
